services:
  database:
    image: postgres:10.17
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=4732"
      - "POSTGRES_DB=usuario"
    ports:
      - "5441:5432"
    volumes:
      - pg-data:/var/lib/postgresql/usuariosdb
volumes:
  pg-data: